FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY . .

EXPOSE 3000

ENV NODE_ENV=development
ENV PORT=3000
ENV HOST=0.0.0.0

CMD ["npm", "run", "dev"]














